# Generated by Django 5.1 on 2024-09-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Mid'), ('L', 'Large')], default='S', max_length=1)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chicken')),
            ],
        ),
    ]
